---
- hosts: static_page
  become_method: sudo
  become: yes

  vars:
    packages:
      - git
      - apache2
    repo_url: https://github.com/Yaowenjie/static_page.git
    dest_dir: /var/www/html/static_page

  tasks:
    - name: Apt update
      run_once: true
      apt:
        update_cache: yes

    - name: Ensure packages installed
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - name: Git clone remote static page repo
      git:
        repo={{ repo_url }}
        dest={{ dest_dir }}
        update=yes
